image: Visual Studio 2017

environment:
  nuspec_file: .\Unic.Bob.Muck.nuspec
  nuget_packageId: Unic.Bob.Muck

install:
  - choco install gitversion.portable -y
  - ps: gitversion /l console /output buildserver
  - ps: . .\restore.ps1
  - cmd: ECHO nuget pack %nuspec_file% -version "%GitVersion_NuGetVersion%"
  - cmd: ECHO %nuget_packageId%
 
#  - cmd: nuget pack %nuspec_file% -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
#  - cmd: appveyor PushArtifact "%nuget_packageId%.%GitVersion_NuGetVersion%.nupkg"

assembly_info:
  patch: false

build: off

#before_test:
#  - ps: Import-Module "./packages/pester/tools/pester.psm1"

#test_script:
#  - ps: Invoke-Pester ./src -OutputFile TestResults.xml -OutputFormat NUnitXml -EnableExit
