image: Visual Studio 2017

environment:
  Nuspec_File: .\Unic.Bob.Muck.nuspec
  Artefact_Output_Dir: .\output

install:
  - choco install gitversion.portable -y
  - ps: gitversion /l console /output buildserver
  - ps: . .\restore.ps1
  - cmd: ECHO nuget pack %Nuspec_File% -version "%GitVersion_NuGetVersion%" -OutputDirectory %Artefact_Output_Dir%

assembly_info:
  patch: false

build: off

before_test:
  - ps: Import-Module "./packages/pester/tools/pester.psm1"

test_script:
  - ps: Invoke-Pester ./src -OutputFile TestResults.xml -OutputFormat NUnitXml -EnableExit

artifacts:
  - path: '.\%Artefact_Output_Dir%\*.nupkg'
