version: '{build}'
image: Visual Studio 2017
environment:
  PAKET_USER:
    secure: gJWu6tlxq9hCQZ20SSyX7g==
  PAKET_PASSWORD:
    secure: GrAGau+8oESef/W0sTTmvA==
  NuGet_PackageId: Unic.Bob.Muck
  Nuspec_File: .\%NuGet_PackageId%.nuspec
  Artefact_Output_Dir: .\output

install:
  - choco install gitversion.portable -y
  - ps: gitversion /l console /output buildserver
  - ps: . .\restore.ps1
  - cmd: nuget pack %Nuspec_File% -version "%GitVersion_NuGetVersionV2%" -OutputDirectory %Artefact_Output_Dir%
  - cmd: appveyor PushArtifact %Artefact_Output_Dir%\%NuGet_PackageId%.%GitVersion_NuGetVersionV2%.nupkg"

assembly_info:
  patch: false

build: off
test: off

#before_test:
#  - ps: Import-Module "./packages/pester/tools/pester.psm1"

#test_script:
#  - ps: Invoke-Pester ./src -OutputFile TestResults.xml -OutputFormat NUnitXml -EnableExit
