mode: ContinuousDelivery
branches:
  release[/-]:
    tag: release
  hotfix[/-]:
    tag: hotfix
    prevent-increment-of-merged-branch-version: true
  master:    
    increment: Minor
  support[/-]:
    tag: support
